name: Security Monitoring

on:
  schedule:
    # Run weekly security checks on Mondays at 2 AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  security-audit:
    name: Weekly Security Audit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Install dependencies
      run: |
        uv sync --group dev
        uv pip install bandit[toml] safety pip-audit

    - name: Run Bandit security checks
      run: |
        uv run bandit -r py_schemax -f json -o bandit-report.json
        uv run bandit -r py_schemax

    - name: Run Safety CLI to check for vulnerabilities
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}

    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

    - name: Create issue on security findings
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const title = '🚨 Weekly Security Audit Failed';
          const body = `
          The weekly security audit has detected potential security issues.

          Please review the security reports in the workflow artifacts:
          - **Bandit Report**: Static analysis security findings
          - **Safety Report**: Known vulnerabilities in dependencies

          **Workflow Run**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          This issue was automatically created by the security monitoring workflow.
          `;

          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['security', 'automated']
          });
